language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then echo 'error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

script: phpunit -c tests/

